[project]
site_name = "Reliauk's Blog"

site_url = "https://reliauk.github.io/"

site_description = "Reliauk's Blog"
site_author = "Reliauk"

[project.theme]

language = "zh"
logo = "/assets/logo.png"
favicon = "/assets/logo.png"

features = [
  "navigation.instant",           # 即时导航（推荐）
  "navigation.instant.prefetch",  # 预加载（推荐，提升性能）
  "navigation.tracking",          # 锚点跟踪
  "navigation.tabs",              # 导航标签
  "navigation.sections",          # 导航部分
  "navigation.top",               # 返回顶部按钮

  "search.suggest",               # 搜索建议
  "search.highlight",             # 搜索高亮

  "content.code.copy",            # 代码复制按钮（推荐）
]

[[project.theme.palette]]
media = "(prefers-color-scheme: light)"
scheme = "default"
primary = "green"    # 主色调
accent = "green"     # 强调色

